{{ if .Values.ingressRoute.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.ingressRoute.host }}
  namespace: {{ .Values.namespace }}
  labels:
    component: homepage
    release: {{ .Release.Name }}
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    {{ if .Values.ingressRoute.isRoot }}
    match: Host(`{{ .Values.ingressRoute.host }}`) || Host(`www.{{ .Values.ingressRoute.host }}`)
    middlewares:
    - name: stripwww
    {{ else }}
    match: Host(`{{ .Values.ingressRoute.host }}`)
    {{ end }}
    priority: 10
    services:
    - name: {{ .Release.Name }}
      port: {{ .Values.app.port }}
      namespace: {{ .Values.namespace }}
  tls:
    secretName: {{ .Values.ingressRoute.host }}-tls
{{ end }}
