replicaCount: 1

app:
  port: 7000

image:
  repository:
  tag: main
  pullPolicy: Always

env:
  DATABASE_CONNECTION_STRING:

ingressRoute:
  enabled: false
  isRoot: false
  host:
  tls:
    issuer: