replicaCount: 1

image:
  repository:
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 7000

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

ingressRoute:
  enabled: false
  host:
  tls:
    issuer:
